--- #YAML:1.0
name:                Net-Squid-Auth-Engine
version:             0.01.03
abstract:            External Credentials Authentication for Squid HTTP Cache
license:             ~
author:              
    - Luis Motta Campos <lmc@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::General:               2.38
    IO::Handle:                    0
    Test::More:                    0
    version:                       0.74
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
